modLoader="javafml"
loaderVersion="[38,)"
license="MIT"
issueTrackerURL="https://github.com/SilentChaos512/SilentGemsChaos/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/silents-gems-chaos"
#logoFile="examplemod.png" #optional
credits=""
authors="SilentChaos512"

[[mods]]
    modId="silentgems_chaos"
    version="${file.jarVersion}"
    displayName="Silent's Gems: Chaos"
    #updateJSONURL="https://raw.githubusercontent.com/SilentChaos512/SilentGemsChaos/1.18.x/update.json"
    description='''
    Downloads: https://www.curseforge.com/minecraft/mc-mods/silents-gems-chaos (I do not upload anywhere else)
    Changelog: https://github.com/SilentChaos512/SilentGemsChaos/blob/1.18.x/CHANGELOG.md
    Source: https://github.com/SilentChaos512/SilentGemsChaos/
    Issues: https://github.com/SilentChaos512/SilentGemsChaos/issues
    '''

[[dependencies.silentgems_chaos]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.silentgems_chaos]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.silentgems_chaos]]
    modId="silentlib"
    mandatory=true
    versionRange="[6,7)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.silentgems_chaos]]
    modId="silentgems"
    mandatory=true
    versionRange="[4,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.silentgems_chaos]]
    modId="silentgear"
    mandatory=false
    versionRange="[2.8,)"
    ordering="AFTER"
    side="BOTH"
